# Generated by Django 4.1.2 on 2022-10-16 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200)),
                ("shipping_address", models.CharField(max_length=200)),
                (
                    "shipping_city",
                    models.CharField(
                        choices=[
                            ("Ivano-Frankivsk", "Ivano-Frankivsk"),
                            ("Kiyv", "Kiyv"),
                            ("Lviv", "Lviv"),
                            ("Odessa", "Odessa"),
                            ("Chernivtsi", "Chernivtsi"),
                            ("Kherson", "Kherson"),
                            ("Zaporizhzhia", "Zaporizhzhia"),
                            ("Poltava", "Poltava"),
                        ],
                        default="Ivano-Frankivsk",
                        max_length=200,
                    ),
                ),
                ("delivery_address", models.CharField(max_length=200)),
                (
                    "delivery_city",
                    models.CharField(
                        choices=[
                            ("Ivano-Frankivsk", "Ivano-Frankivsk"),
                            ("Kiyv", "Kiyv"),
                            ("Lviv", "Lviv"),
                            ("Odessa", "Odessa"),
                            ("Chernivtsi", "Chernivtsi"),
                            ("Kherson", "Kherson"),
                            ("Zaporizhzhia", "Zaporizhzhia"),
                            ("Poltava", "Poltava"),
                        ],
                        default="Ivano-Frankivsk",
                        max_length=200,
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("lightweight", "lightweight"),
                            ("halfweight", "halfweight"),
                            ("heavyweight", "heavyweight"),
                        ],
                        default="lightweight",
                        max_length=200,
                    ),
                ),
                ("datetime", models.DateField()),
                ("add_info", models.TextField(blank=True, null=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
