# Generated by Django 4.1.2 on 2022-10-16 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transport_app", "0002_companytaxes_workers_orders_is_completed_salaries"),
    ]

    operations = [
        migrations.AddField(
            model_name="workers",
            name="worker_position",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
