# Generated by Django 4.1.2 on 2022-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport_app", "0006_salaries_ordrer_id_alter_salaries_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaries",
            name="date_added",
            field=models.DateField(auto_now=True),
        ),
    ]
