# Generated by Django 4.1.2 on 2022-10-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport_app", "0007_salaries_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="workers",
            name="percent_from_order",
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
