# Generated by Django 4.1.2 on 2022-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport_app", "0008_workers_percent_from_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryTaxes",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("day", models.IntegerField(default=1)),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=1,
                    ),
                ),
                ("year", models.IntegerField()),
                ("taxes_on_profit", models.FloatField()),
                ("taxes_of_workers", models.FloatField()),
                ("euv_of_workers", models.FloatField()),
            ],
        ),
    ]
