# Generated by Django 4.1.2 on 2022-10-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport_app", "0009_summarytaxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summarytaxes",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="summarytaxes",
            name="year",
            field=models.IntegerField(default=2022),
        ),
    ]
