# Generated by Django 4.1.2 on 2022-10-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport_app", "0010_alter_summarytaxes_id_alter_summarytaxes_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summarytaxes",
            name="euv_of_workers",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="summarytaxes",
            name="taxes_of_workers",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="summarytaxes",
            name="taxes_on_profit",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
