# Generated by Django 4.1.2 on 2022-10-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport_app", "0011_alter_summarytaxes_euv_of_workers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="summarytaxes",
            name="summary_vat",
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companytaxes",
            name="create_date",
            field=models.DateField(auto_now=True),
        ),
    ]
