# Generated by Django 4.1.2 on 2022-10-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport_app", "0013_alter_summarytaxes_summary_vat"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Salaries",
            new_name="SalaryTax",
        ),
    ]
